# Indicate what region to deploy the resources into
generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "aws" {
  region = "us-east-1"
}
EOF
}

/*
generate "backend" {
  path      = "${path_relative_to_include()}/../backend.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
terraform {
  backend "s3" {
    bucket         = "my-terragrunt-tf-state"
    key            = "${get_parent_terragrunt_dir()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
EOF
}
# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-terragrunt-tf-state"
    key            = "C:/Users/ADMIN/Desktop/sameh-github-repos/terragrunt-lab/prod/ue1/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}

generate "backend" {
  path      = "${path_relative_to_include()}/../backend.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
terraform {
  backend "s3" {
    bucket         = "my-terragrunt-tf-state"
    key            = "${get_parent_terragrunt_dir()}/${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
EOF
}

# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-terragrunt-tf-state"
    key            = "C:/Users/ADMIN/Desktop/sameh-github-repos/terragrunt-lab/prod/ue1/vpc/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
*/

/*
C:\Users\ADMIN\Desktop\sameh-github-repos\terragrunt-lab\prod\ue1\vpc\.terragrunt-cache\HIbMDspLmTT3-OyTPU6CXM3E3C4\vpc\backend.tf:
el mfrood ykon el path mn3'er VPC at the end 3lshan module el vpc bytshal bl folder lma by3ml download
#generate backend
generate "backend" {
  path      = "${path_relative_to_include()}/backend.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
terraform {
  backend "s3" {
    bucket         = "my-terragrunt-tf-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
EOF
}
*/

